# HACKY_RACCOON_CI_BASE_PATH must be defined as a project level variable
# this is done in this way to test some things of hacky raccon ci templates repo
include:
  - remote: '${HACKY_RACCOON_CI_BASE_PATH}/templates/.base_workflow.yml'
  - remote: '${HACKY_RACCOON_CI_BASE_PATH}/templates/.base_build_docker_img.yml'

variables:
  BUILD_IMAGE_RUNNER_TAG: hacky-raccoon-docker-amd64
  DOCKER_IMAGE_ARCH: amd64              # Docker image architecture
  DOCKERFILES_DIR: .gci                 # Dockerfile directory

stages:
  - build_image
  - pages

build-image-branch:
  extends: 
    - .build-image
    - .branch
  variables:
    IMAGE: ${CI_REGISTRY_IMAGE}/${DOCKER_IMAGE_ARCH}/${CI_COMMIT_REF_NAME}:${CI_COMMIT_SHORT_SHA}

build-image-latest:
  extends: 
    - .build-image
    - .latest
  variables:
    IMAGE: ${CI_REGISTRY_IMAGE}/${DOCKER_IMAGE_ARCH}:latest

build-image-tag:
  extends: 
    - .build-image
    - .tag
  variables:
    IMAGE: ${CI_REGISTRY_IMAGE}/${DOCKER_IMAGE_ARCH}/tag:${CI_COMMIT_REF_NAME}

.pages:
  stage: pages
  script:
    - sphinx-build -d _build/doctrees . _build/html
    - mv _build/html public/
  artifacts:
    paths:
    - public
  tags:
    - hacky-raccoon-docker-amd64

pages-branch:
  image: ${CI_REGISTRY_IMAGE}/${DOCKER_IMAGE_ARCH}/${CI_COMMIT_REF_NAME}:${CI_COMMIT_SHORT_SHA}
  extends:
    - .pages
    - .branch

pages-latest:
  image: ${CI_REGISTRY_IMAGE}/${DOCKER_IMAGE_ARCH}:latest
  extends:
    - .pages
    - .latest

pages-tag:
  image: ${CI_REGISTRY_IMAGE}/${DOCKER_IMAGE_ARCH}/tag:${CI_COMMIT_REF_NAME}
  extends:
    - .pages
    - .tag
